version: "3.8"
services:
  app:
    container_name: app
    build:
      context: . # The path of the Dockerfile
    volumes:
      - .:/usr/src/app
    depends_on:
      - db
    working_dir: /usr/src/app
    environment:
      SERVICE_NAME: app
      DB_CONNECTION: mysql
      DB_DRIVER: mysql
      DB_HOST: db
      DB_PORT: 3306
    networks:
      - app_network

  nginx:
    container_name: nginx
    build:
      context: ./nginx/. # The path of the Dockerfile
    volumes:
      - "./public:/usr/src/app/public"
    environment:
      NGINX_FPM_HOST: app
      NGINX_ROOT: /usr/src/app/public
    ports:
      - "8000:80"
    depends_on:
      - app
    networks:
      - app_network

  db:
    image: mysql:5
    container_name: db
    restart: always
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
