version: "2.4"

volumes:
  logs:
    driver: local

services:
  php:
    container_name: php
    build:
      target: base
      context: .
    working_dir: /var/www/html
    environment:
      docker: "true"
    volumes:
      - .:/var/www/html
      - logs:/var/www/html/logs
    networks:
      backend:
        aliases:
          - php
  nginx:
    container_name: nginx
    image: nginx
    volumes:
      - ./opt/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      php:
        condition: service_started
    ports:
      - "8080:80"
    networks:
      backend:
        aliases:
          - nginx
  mariadb:
    container_name: db
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    ports:
      - "3306:3306"
    networks:
      backend:
        aliases:
          - db
networks:
  backend:
    name: backend-network
