version: "2.4"

volumes:
  logs:
    driver: local

services:
  php:
    build:
      target: base
      context: .
    working_dir: /var/www/html
    environment:
      docker: "true"
    # depends_on:
    #   mariadb:
    #     condition: service_healthy
    volumes:
      - .:/var/www/html
      - logs:/var/www/html/logs

  nginx:
    image: nginx
    volumes:
      - ./opt/nginx/vhost.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      php:
        condition: service_started
    ports:
      - "8080:80"

  mariadb:
    image: mariadb:10
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    # healthcheck:
    #   interval: 5s
    #   test: ["CMD", "bash", "-c", "echo > /dev/tcp/localhost/3306"]
    ports:
      - "3306:3306"
